---
title: 绘图尝试4.0.2 绘制流程图
author: 鱼记苦瓜糖
date: '2019-06-26'
slug: 绘图尝试4-0-2-绘制流程图
categories:
  - R
tags: []
---
每日一问：今天，你为R疯狂了吗？  
是的。  

以下流程图虽然粗糙笨拙，但使用简单的操作做出来仍然成就感满满。  
本次使用R进行了流程图的绘制。  
以下是语句。  
或许将具体的汉字名称换为符号表达语句会更加简洁。之后会再尝试！  

①检索所在专业的流程图
```{r}
library(DiagrammeR)
grViz("
digraph fig{
sc[label='四川大学',shape=circle]
sc -> '文科类学院'->'管理类学院'->'公共管理学院'->'图书情报与档案管理'->'信息资源管理'
}")

```
②之前的图111
```{r}
library(DiagrammeR)
grViz("
digraph fig{
sc[label='“数字四川”体系框架',shape=box]
sc -> '数字自然生态'
'数字自然生态'->'智慧数字土地监测'
'数字自然生态'->'智慧数字动物资源'
'数字自然生态'->'智慧数字植被资源'
'数字自然生态'->'智慧数字矿产资源'
'数字自然生态'->'智慧数字大气监测'
'数字自然生态'->'智慧数字水利资源'
'数字自然生态'->'智慧数字灾害监防'
sc -> '数字社会生态'
'数字社会生态'->'智慧数字工业（制造业）'
'数字社会生态'->'智慧数字社交'
'数字社会生态'->'智慧数字文化'
'数字社会生态'->'智慧数字医疗'
'数字社会生态'->'智慧数字农业'
'数字社会生态'->'智慧数字教育'
'数字社会生态'->'智慧数字旅游'
'数字社会生态'->'智慧数字社会'
'数字社会生态'->'智慧数字减灾'
}")

```
③之前的图222
```{r}
library(DiagrammeR)
grViz("
digraph fig{
sc[label='四川省“智慧文化之非物质文化遗产”体系设计',shape=box]
sc -> '基本原则'
'基本原则'->'智能化数字化原则'
'基本原则'->'区域协调发展原则'
'基本原则'->'资源优化配置原则 '
'基本原则'->'因地制宜特色化原则 '
'基本原则'->'科学化合理化原则'
sc -> '主要内容'
'主要内容'->'服务用户'
'主要内容'->'实体设施地区分布'
'主要内容'->'应用设施和技术'
'应用设施和技术'->'平台软件应用层'
'应用设施和技术'->'数据存储和管理层'
'应用设施和技术'->'智能化控制层';
'主要内容'->'文化组织'
'文化组织'->'政府组织'->'组织人员'
'文化组织'->'社会组织'->'组织人员'
'组织人员'->'文化专职人员'
'组织人员'->'服务志愿者员'
'主要内容'->'人员素养'
'主要内容'->'数据需求规划'
'数据需求规划'->'基础文化地理数据需求'
'数据需求规划'->'专题数据需求'
'数据需求规划'->'元数据需求'
'数据需求规划'->'数据获取需求'
'数据需求规划'->'数据质量和控制需求'
'数据需求规划'->'数据交换和数据安全需求'
'主要内容'->'工程阶段'
'主要内容'->'安全规划'
}")
```

 THE END